# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='usuarioAlteracao',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='usuarioCriacao',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='usuarioAlteracao',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='usuarioCriacao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='usuarioAlteracao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='usuarioCriacao',
        ),
        migrations.RemoveField(
            model_name='regional',
            name='usuarioAlteracao',
        ),
        migrations.RemoveField(
            model_name='regional',
            name='usuarioCriacao',
        ),
    ]
