# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171128_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='descricao',
            field=models.CharField(default='', max_length=50),
        ),
    ]
