# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171128_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='idPessoa',
        ),
        migrations.AddField(
            model_name='grupo',
            name='idPessoa',
            field=models.ManyToManyField(to='api.Pessoa', verbose_name='Membros'),
        ),
    ]
