# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171128_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='regional',
            options={'verbose_name_plural': 'Regionais'},
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='idPessoa',
            new_name='membros',
        ),
    ]
